site_name: Lunar Tear
site_url: https://vasconii.github.io/guide/
site_author: vasconii
repo_name: vasconii/guide
repo_url: https://github.com/vasconii/guide

theme:
  name: material
  features:
    - content.code.copy
  palette:
    scheme: slate
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
    - Home: index.md
    - Setup: Setup.md
