site_name: Lunar Tear Installation Guide
site_url: https://vasconii.github.io/guide/
site_author: vasconii
repo_name: vasconii/guide
repo_url: https://github.com/vasconii/guide

theme:
  name: material
  features:
    - content.code.copy
  custom_dir: overrides
  palette:
    scheme: slate
    
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list

nav:
    - Home: index.md
    - Guide: Setup.md
    - Static IP (Work in Progress): IP_guide.md
    - Go Troubleshooting: Go_troubleshooting.md
     
    
    

plugins:
    - search
    - git-revision-date-localized:
        type: datetime
         
extra_javascript:
  - javascripts/external-links.js